/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import demo.validations.ValidationUtils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
        @Test void validateRun() {
                // Basic
                assertFalse(ValidationUtils.validateRun(""));
                assertFalse(ValidationUtils.validateRun(" "));
                assertFalse(ValidationUtils.validateRun("12345678912"));
                assertFalse(ValidationUtils.validateRun("1234567891"));

                // Must pass
                assertTrue(ValidationUtils.validateRun("11123432"));
                assertTrue(ValidationUtils.validateRun("1123432"));
                assertTrue(ValidationUtils.validateRun("1111111"));

                // Will it break?
                assertFalse(ValidationUtils.validateRun("111111111111111111111"));
                assertFalse(ValidationUtils.validateRun("       "));
                assertFalse(ValidationUtils.validateRun("--------"));
                assertFalse(ValidationUtils.validateRun("''''''''"));
        }

        @Test void validateDv() {
                // Basic
                assertFalse(ValidationUtils.validateDv(""));
                assertFalse(ValidationUtils.validateDv(" "));
                assertFalse(ValidationUtils.validateDv("0"));
                assertFalse(ValidationUtils.validateDv("-"));

                // Must pass
                assertTrue(ValidationUtils.validateDv("1"));
                assertTrue(ValidationUtils.validateDv("6"));
                assertTrue(ValidationUtils.validateDv("K"));

                // Will it break?
                assertFalse(ValidationUtils.validateRun("'"));
                assertFalse(ValidationUtils.validateRun("1111111111111111"));
                assertFalse(ValidationUtils.validateRun("''"));
                assertFalse(ValidationUtils.validateRun("k"));
        }

        @Test void validateTel() {
                // Basic
                assertFalse(ValidationUtils.validateTel(""));
                assertFalse(ValidationUtils.validateTel(" "));
                assertFalse(ValidationUtils.validateTel("1234"));
                assertFalse(ValidationUtils.validateTel("abc"));

                // Must pass
                assertTrue(ValidationUtils.validateTel("12345678"));
                assertTrue(ValidationUtils.validateTel("+5290909023"));
                assertTrue(ValidationUtils.validateTel("+569 90909023"));

                // Will it break?
                assertFalse(ValidationUtils.validateTel("12345678901234567"));
                assertFalse(ValidationUtils.validateTel("+1abc123456"));
                assertFalse(ValidationUtils.validateTel("+569 12312321321321321"));
        }
}
