/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import demo.models.MysqlConnect;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;

class DbConnectionTest {
        private static final MysqlConnect mysqlConn = new MysqlConnect("test.env");

        @Test
        void testDatabaseConnection() {
                try (Connection connection = mysqlConn.connect()) {
                        assertNotNull(connection, "Connection should not be null");
                        assertTrue(connection.isValid(5), "Connection should be valid");

                        System.out.println("Database connection successful!");
                } catch (SQLException e) {
                        fail("Error connecting to the database: " + e.getMessage());
                }
        }
}
